### ISSUE TITLE
Windows可以使用吗

### ISSUE THREAD

**Issue by Hujiazeng** [lipku/python_rtmpstream#2]

**Comment by lipku** [comment]
windows应该也能用，没有实际测过。在windows下编译ffmpeg，CMakefilelist里指向编译后的路径

**Comment by OneMobPsycho100** [comment]
> windows应该也能用，没有实际测过。在windows下编译ffmpeg，CMakefilelist里指向编译后的路径

我在win下编译了ffmpeg，在安装rtmp_streaming的时候有一些函数还有头文件在windows无法使用，我尝试用gpt改了一下编译成功了，运行的时候又报了个DLL load failed...

**Comment by huyppppppp** [comment]
> > windows应该也能用，没有实际测过。在windows下编译ffmpeg，CMakefilelist里指向编译后的路径
> 
> 我在win下编译了ffmpeg，在安装rtmp_streaming的时候有一些函数还有头文件在windows无法使用，我尝试用gpt改了一下编译成功了，运行的时候又报了个DLL load failed...

您好，我也是在win下编译了，安装的时候出现了这个错
line 345, in run
          self.build_extensions()
        File "D:\Python_ralated\anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "D:\Python_ralated\anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "D:\shixi\nerfstream\python_rtmpstream\python\setup.py", line 116, in build_extension
          subprocess.check_call(
        File "D:\Python_ralated\anaconda\envs\nerfstream\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rtmp_streaming
  Running setup.py clean for rtmp_streaming
Failed to build rtmp_streaming
ERROR: Could not build wheels for rtmp_streaming, which is required to install pyproject.toml-based projects

请问您有遇见过吗？我的cmakelists.txt是这样的
set(PYTHON_EXECUTABLE /d/Python_ralated/anaconda/envs/nerfstream/python.exe)

include_directories("/d/shixi/ffmpegbianyi/FFmpeg-n5.1.2-install/include")
link_directories("/d/shixi/ffmpegbianyi/FFmpeg-n5.1.2-install/lib")
find_library(AVCODEC_LIBRARY avcodec)
find_library(AVFORMAT_LIBRARY avformat)
find_library(AVUTIL_LIBRARY avutil)
find_library(SWSCALE_LIBRARY swscale)不知道这样写是否正确的？

**Comment by OneMobPsycho100** [comment]
> > > windows应该也能用，没有实际测过。在windows下编译ffmpeg，CMakefilelist里指向编译后的路径
> > 
> > 
> > 我在win下编译了ffmpeg，在安装rtmp_streaming的时候有一些函数还有头文件在windows无法使用，我尝试用gpt改了一下编译成功了，运行的时候又报了个DLL load failed...
> 
> 您好，我也是在win下编译了，安装的时候出现了这个错 line 345, in run self.build_extensions() File "D:\Python_ralated\anaconda\envs\nerfstream\lib\site-packages\setuptools_distutils\command\build_ext.py", line 467, in build_extensions self._build_extensions_serial() File "D:\Python_ralated\anaconda\envs\nerfstream\lib\site-packages\setuptools_distutils\command\build_ext.py", line 493, in _build_extensions_serial self.build_extension(ext) File "D:\shixi\nerfstream\python_rtmpstream\python\setup.py", line 116, in build_extension subprocess.check_call( File "D:\Python_ralated\anaconda\envs\nerfstream\lib\subprocess.py", line 369, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release']' returned non-zero exit status 1. [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for rtmp_streaming Running setup.py clean for rtmp_streaming Failed to build rtmp_streaming ERROR: Could not build wheels for rtmp_streaming, which is required to install pyproject.toml-based projects
> 
> 请问您有遇见过吗？我的cmakelists.txt是这样的 set(PYTHON_EXECUTABLE /d/Python_ralated/anaconda/envs/nerfstream/python.exe)
> 
> include_directories("/d/shixi/ffmpegbianyi/FFmpeg-n5.1.2-install/include") link_directories("/d/shixi/ffmpegbianyi/FFmpeg-n5.1.2-install/lib") find_library(AVCODEC_LIBRARY avcodec) find_library(AVFORMAT_LIBRARY avformat) find_library(AVUTIL_LIBRARY avutil) find_library(SWSCALE_LIBRARY swscale)不知道这样写是否正确的？

link_directories("/d/shixi/ffmpegbianyi/FFmpeg-n5.1.2-install/bin") 指向bin目录试试

**Comment by OneMobPsycho100** [comment]
我已经放弃了，在win下面编译ffmpeg总是有个乱码错误，最后还是在linux上交叉编译的，不知道最后加载动态链接库是不是和这个有关系，我现在用macos跑一下看看

**Comment by OneMobPsycho100** [comment]
> > 我已经放弃了，在win下面编译ffmpeg总是有个乱码错误，最后还是在linux上交叉编译的，不知道最后加载动态链接库是不是和这个有关系，我现在用macos跑一下看看
> 
> 我刚刚编译了ffmpeg之后安装rtmp_streaming的时候也遇到了头文件无法使用的问题，解决完之后这个库可以调用了，但是运行测试代码的时候又出错了 Connection to tcp://localhost:1935 failed: Error number -138 occurred [rtmp @ 000001b786cf5040] Cannot open connection tcp://localhost:1935 failed to open stream output context, stream will not work 还得再查

感觉你的应该是可以用，这是开始推流了，你本地没起服务。

**Comment by huyppppppp** [comment]
> > > 我已经放弃了，在win下面编译ffmpeg总是有个乱码错误，最后还是在linux上交叉编译的，不知道最后加载动态链接库是不是和这个有关系，我现在用macos跑一下看看
> > 
> > 
> > 我刚刚编译了ffmpeg之后安装rtmp_streaming的时候也遇到了头文件无法使用的问题，解决完之后这个库可以调用了，但是运行测试代码的时候又出错了 Connection to tcp://localhost:1935 failed: Error number -138 occurred [rtmp @ 000001b786cf5040] Cannot open connection tcp://localhost:1935 failed to open stream output context, stream will not work 还得再查
> 
> 感觉你的应该是可以用，这是开始推流了，你本地没起服务。

嗯嗯，好像是这样

**Comment by OneMobPsycho100** [comment]
> > > > 我已经放弃了，在win下面编译ffmpeg总是有个乱码错误，最后还是在linux上交叉编译的，不知道最后加载动态链接库是不是和这个有关系，我现在用macos跑一下看看
> > > 
> > > 
> > > 我刚刚编译了ffmpeg之后安装rtmp_streaming的时候也遇到了头文件无法使用的问题，解决完之后这个库可以调用了，但是运行测试代码的时候又出错了 Connection to tcp://localhost:1935 failed: Error number -138 occurred [rtmp @ 000001b786cf5040] Cannot open connection tcp://localhost:1935 failed to open stream output context, stream will not work 还得再查
> > 
> > 
> > 感觉你的应该是可以用，这是开始推流了，你本地没起服务。
> 
> 嗯嗯，好像是这样

我又换了台全新的windows机器，ffmpeg编译也很顺利，但是仍然出现了这个错误，感觉是我哪个步骤错了。 请问下你编译ffmpg的时候加了什么扩展吗，还有能否分享一下你修改后的代码呢，非常感谢。PS D:\dev\ffmpeg\python_rtmpstream\python> python .\test_stream.py
Traceback (most recent call last):
  File "D:\dev\ffmpeg\python_rtmpstream\python\test_stream.py", line 4, in <module>
    from rtmp_streaming import StreamerConfig, Streamer
ImportError: DLL load failed while importing rtmp_streaming: 找不到指定的模块。

**Comment by huyppppppp** [comment]
> > > > > 我已经放弃了，在win下面编译ffmpeg总是有个乱码错误，最后还是在linux上交叉编译的，不知道最后加载动态链接库是不是和这个有关系，我现在用macos跑一下看看
> > > > 
> > > > 
> > > > 我刚刚编译了ffmpeg之后安装rtmp_streaming的时候也遇到了头文件无法使用的问题，解决完之后这个库可以调用了，但是运行测试代码的时候又出错了 Connection to tcp://localhost:1935 failed: Error number -138 occurred [rtmp @ 000001b786cf5040] Cannot open connection tcp://localhost:1935 failed to open stream output context, stream will not work 还得再查
> > > 
> > > 
> > > 感觉你的应该是可以用，这是开始推流了，你本地没起服务。
> > 
> > 
> > 嗯嗯，好像是这样
> 
> 我又换了台全新的windows机器，ffmpeg编译也很顺利，但是仍然出现了这个错误，感觉是我哪个步骤错了。 请问下你编译ffmpg的时候加了什么扩展吗，还有能否分享一下你修改后的代码呢，非常感谢。PS D:\dev\ffmpeg\python_rtmpstream\python> python .\test_stream.py Traceback (most recent call last): File "D:\dev\ffmpeg\python_rtmpstream\python\test_stream.py", line 4, in from rtmp_streaming import StreamerConfig, Streamer ImportError: DLL load failed while importing rtmp_streaming: 找不到指定的模块。

ffmpeg编译，我是按照https://blog.csdn.net/u012559967/article/details/134035253这个博文编译的，好像没有什么问题，如果你需要，我可以把文件打包发给你邮件

**Comment by OneMobPsycho100** [comment]
> > > > > > 我已经放弃了，在win下面编译ffmpeg总是有个乱码错误，最后还是在linux上交叉编译的，不知道最后加载动态链接库是不是和这个有关系，我现在用macos跑一下看看
> > > > > 
> > > > > 
> > > > > 我刚刚编译了ffmpeg之后安装rtmp_streaming的时候也遇到了头文件无法使用的问题，解决完之后这个库可以调用了，但是运行测试代码的时候又出错了 Connection to tcp://localhost:1935 failed: Error number -138 occurred [rtmp @ 000001b786cf5040] Cannot open connection tcp://localhost:1935 failed to open stream output context, stream will not work 还得再查
> > > > 
> > > > 
> > > > 感觉你的应该是可以用，这是开始推流了，你本地没起服务。
> > > 
> > > 
> > > 嗯嗯，好像是这样
> > 
> > 
> > 我又换了台全新的windows机器，ffmpeg编译也很顺利，但是仍然出现了这个错误，感觉是我哪个步骤错了。 请问下你编译ffmpg的时候加了什么扩展吗，还有能否分享一下你修改后的代码呢，非常感谢。PS D:\dev\ffmpeg\python_rtmpstream\python> python .\test_stream.py Traceback (most recent call last): File "D:\dev\ffmpeg\python_rtmpstream\python\test_stream.py", line 4, in from rtmp_streaming import StreamerConfig, Streamer ImportError: DLL load failed while importing rtmp_streaming: 找不到指定的模块。
> 
> ffmpeg编译，我是按照[https://blog.csdn.net/u012559967/article/details/134035253这个博文编译的，好像没有什么问题，如果你需要，我可以把文件打包发给你邮件](https://blog.csdn.net/u012559967/article/details/134035253%E8%BF%99%E4%B8%AA%E5%8D%9A%E6%96%87%E7%BC%96%E8%AF%91%E7%9A%84%EF%BC%8C%E5%A5%BD%E5%83%8F%E6%B2%A1%E6%9C%89%E4%BB%80%E4%B9%88%E9%97%AE%E9%A2%98%EF%BC%8C%E5%A6%82%E6%9E%9C%E4%BD%A0%E9%9C%80%E8%A6%81%EF%BC%8C%E6%88%91%E5%8F%AF%E4%BB%A5%E6%8A%8A%E6%96%87%E4%BB%B6%E6%89%93%E5%8C%85%E5%8F%91%E7%BB%99%E4%BD%A0%E9%82%AE%E4%BB%B6)

我的邮箱：874211500@qq.com，非常感谢

**Comment by zhangdanfeng888** [comment]
> > > > 我已经放弃了，在win下面编译ffmpeg总是有个乱码错误，最后还是在linux上交叉编译的，不知道最后加载动态链接库是不是和这个有关系，我现在用macos跑一下看看
> > > 
> > > 
> > > 我刚刚编译了ffmpeg之后安装rtmp_streaming的时候也遇到了头文件无法使用的问题，解决完之后这个库可以调用了，但是运行测试代码的时候又出错了 Connection to tcp://localhost:1935 failed: Error number -138 occurred [rtmp @ 000001b786cf5040] Cannot open connection tcp://localhost:1935 failed to open stream output context, stream will not work 还得再查
> > 
> > 
> > 感觉你的应该是可以用，这是开始推流了，你本地没起服务。
> 
> 嗯嗯，好像是这样

请问一下你的CMakeLists.txt是怎么写的呢？

**Comment by huyppppppp** [comment]
> > > > > 我已经放弃了，在win下面编译ffmpeg总是有个乱码错误，最后还是在linux上交叉编译的，不知道最后加载动态链接库是不是和这个有关系，我现在用macos跑一下看看
> > > > 
> > > > 
> > > > 我刚刚编译了ffmpeg之后安装rtmp_streaming的时候也遇到了头文件无法使用的问题，解决完之后这个库可以调用了，但是运行测试代码的时候又出错了 Connection to tcp://localhost:1935 failed: Error number -138 occurred [rtmp @ 000001b786cf5040] Cannot open connection tcp://localhost:1935 failed to open stream output context, stream will not work 还得再查
> > > 
> > > 
> > > 感觉你的应该是可以用，这是开始推流了，你本地没起服务。
> > 
> > 
> > 嗯嗯，好像是这样
> 
> 请问一下你的CMakeLists.txt是怎么写的呢？

<img width="578" alt="image" src="https://github.com/lipku/python_rtmpstream/assets/116953013/488bb9f7-8221-4464-a9ea-0283e3382d90"

**Comment by OneMobPsycho100** [comment]
> > > > > 我已经放弃了，在win下面编译ffmpeg总是有个乱码错误，最后还是在linux上交叉编译的，不知道最后加载动态链接库是不是和这个有关系，我现在用macos跑一下看看
> > > > 
> > > > 
> > > > 我刚刚编译了ffmpeg之后安装rtmp_streaming的时候也遇到了头文件无法使用的问题，解决完之后这个库可以调用了，但是运行测试代码的时候又出错了 Connection to tcp://localhost:1935 failed: Error number -138 occurred [rtmp @ 000001b786cf5040] Cannot open connection tcp://localhost:1935 failed to open stream output context, stream will not work 还得再查
> > > 
> > > 
> > > 感觉你的应该是可以用，这是开始推流了，你本地没起服务。
> > 
> > 
> > 嗯嗯，好像是这样
> 
> 请问一下你的CMakeLists.txt是怎么写的呢？
只能打包成功了，但是不能用啊，运行就报加载dll错误，我没弄了，macos下5分钟就搞定了。。。
![image](https://github.com/lipku/python_rtmpstream/assets/38750006/155b05f7-cb3f-4b99-b1fc-dc9bda79c41d)

**Comment by huyppppppp** [comment]
> > > > > > 我已经放弃了，在win下面编译ffmpeg总是有个乱码错误，最后还是在linux上交叉编译的，不知道最后加载动态链接库是不是和这个有关系，我现在用macos跑一下看看
> > > > > 
> > > > > 
> > > > > 我刚刚编译了ffmpeg之后安装rtmp_streaming的时候也遇到了头文件无法使用的问题，解决完之后这个库可以调用了，但是运行测试代码的时候又出错了 Connection to tcp://localhost:1935 failed: Error number -138 occurred [rtmp @ 000001b786cf5040] Cannot open connection tcp://localhost:1935 failed to open stream output context, stream will not work 还得再查
> > > > 
> > > > 
> > > > 感觉你的应该是可以用，这是开始推流了，你本地没起服务。
> > > 
> > > 
> > > 嗯嗯，好像是这样
> > 
> > 
> > 请问一下你的CMakeLists.txt是怎么写的呢？
> > 只能打包成功了，但是不能用啊，运行就报加载dll错误，我没弄了，macos下5分钟就搞定了。。。
> > ![image](https://private-user-images.githubusercontent.com/38750006/317574931-155b05f7-cb3f-4b99-b1fc-dc9bda79c41d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTcyMDAsIm5iZiI6MTcxMTU5NjkwMCwicGF0aCI6Ii8zODc1MDAwNi8zMTc1NzQ5MzEtMTU1YjA1ZjctY2IzZi00Yjk5LWIxZmMtZGM5YmRhNzljNDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAzMzUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkZGE2NjY2NjVlYjg5ZTBiNTFiMWE1NGM0MGZhZTZjOTUxMWM3M2JhZjNmOWU0ZGUwMmVhOGUyMmJiN2YxYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uKW1BFcKPc5SHSw_wZxpbvo-Jz9tfoJ6fnTIMFVtcVw)

<img width="578" alt="屏幕截图 2024-03-28 103827" src="https://github.com/lipku/python_rtmpstream/assets/116953013/8a1c64f7-9237-460f-922f-286d8d4ad321">
我现在也换成linux了，请问你是运行实时数字人那个吗，他整个库太大了，邮件和百度网盘都上传不了

**Comment by OneMobPsycho100** [comment]
> > > > > > > 我已经放弃了，在win下面编译ffmpeg总是有个乱码错误，最后还是在linux上交叉编译的，不知道最后加载动态链接库是不是和这个有关系，我现在用macos跑一下看看
> > > > > > 
> > > > > > 
> > > > > > 我刚刚编译了ffmpeg之后安装rtmp_streaming的时候也遇到了头文件无法使用的问题，解决完之后这个库可以调用了，但是运行测试代码的时候又出错了 Connection to tcp://localhost:1935 failed: Error number -138 occurred [rtmp @ 000001b786cf5040] Cannot open connection tcp://localhost:1935 failed to open stream output context, stream will not work 还得再查
> > > > > 
> > > > > 
> > > > > 感觉你的应该是可以用，这是开始推流了，你本地没起服务。
> > > > 
> > > > 
> > > > 嗯嗯，好像是这样
> > > 
> > > 
> > > 请问一下你的CMakeLists.txt是怎么写的呢？
> > > 只能打包成功了，但是不能用啊，运行就报加载dll错误，我没弄了，macos下5分钟就搞定了。。。
> > > ![image](https://private-user-images.githubusercontent.com/38750006/317574931-155b05f7-cb3f-4b99-b1fc-dc9bda79c41d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTcyMDAsIm5iZiI6MTcxMTU5NjkwMCwicGF0aCI6Ii8zODc1MDAwNi8zMTc1NzQ5MzEtMTU1YjA1ZjctY2IzZi00Yjk5LWIxZmMtZGM5YmRhNzljNDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAzMzUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkZGE2NjY2NjVlYjg5ZTBiNTFiMWE1NGM0MGZhZTZjOTUxMWM3M2JhZjNmOWU0ZGUwMmVhOGUyMmJiN2YxYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uKW1BFcKPc5SHSw_wZxpbvo-Jz9tfoJ6fnTIMFVtcVw)
> 
> <img alt="屏幕截图 2024-03-28 103827" width="578" src="https://private-user-images.githubusercontent.com/116953013/317583178-8a1c64f7-9237-460f-922f-286d8d4ad321.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTc2MzEsIm5iZiI6MTcxMTU5NzMzMSwicGF0aCI6Ii8xMTY5NTMwMTMvMzE3NTgzMTc4LThhMWM2NGY3LTkyMzctNDYwZi05MjJmLTI4NmQ4ZDRhZDMyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwMzQyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDI4ZmVhNjE5YzkzMDQwMzhkMzBiMWJkYzljODMzOWMxYmQ5NTNhMDljN2U2ZGQ4ZmE4ZTI2MmZmNDc3NGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XK11ivpXSriLh94Utz6JQ8037Kc08LvTfEwKvW_RemQ"> 我现在也换成linux了，请问你是运行实时数字人那个吗，他整个库太大了，邮件和百度网盘都上传不了

不是，只是想搞那个直播推流，换了个其它方式也能用，最后也没用这个库

**Comment by zhangdanfeng888** [comment]
折腾了好几天，终于在windows下跑通了，[metahuman-stream](https://github.com/lipku/metahuman-stream)，真不容易

**Comment by qwert1887** [comment]
> 折腾了好几天，终于在windows下跑通了，[metahuman-stream](https://github.com/lipku/metahuman-stream)，真不容易

你好，请问你遇到这个报错了吗`Streamer ImportError: DLL load failed while importing rtmp_streaming: 找不到指定的模块`，我现在卡在这了，换其他的库需要改的地方有点多。DLL load failed的问题，请问有没有什么解决思路呢，感谢

**Comment by ajiansoft** [comment]
一样的编译看起来安装起whl文件了，一运行就报：No module named 'rtmp_streaming'

**Comment by ajiansoft** [comment]
请问DLL load failed的问题是怎么解决的？
