### ISSUE TITLE
执行`pip install .`报错！

### ISSUE THREAD

**Issue by piwawa** [lipku/python_rtmpstream#3]
```
(py39) root@vultr:~/AIGC/metahuman-stream/python_rtmpstream/python# pip install .
Processing /root/AIGC/metahuman-stream/python_rtmpstream/python
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: rtmp-streaming
  Building wheel for rtmp-streaming (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Building with cfg =  Release
      -- The C compiler identification is GNU 11.4.0
      -- The CXX compiler identification is GNU 11.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at CMakeLists.txt:57 (add_subdirectory):
        add_subdirectory given source "pybind11" which is not an existing
        directory.
      
      
      CMake Error at CMakeLists.txt:58 (pybind11_add_module):
        Unknown CMake command "pybind11_add_module".
      
      
      -- Configuring incomplete, errors occurred!
      See also "/root/AIGC/metahuman-stream/python_rtmpstream/python/build/temp.linux-x86_64-cpython-39/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/root/AIGC/metahuman-stream/python_rtmpstream/python/setup.py", line 125, in <module>
          setup(
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/root/AIGC/metahuman-stream/python_rtmpstream/python/setup.py", line 113, in build_extension
          subprocess.check_call(
        File "/root/miniconda3/envs/py39/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/root/AIGC/metahuman-stream/python_rtmpstream/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/root/AIGC/metahuman-stream/python_rtmpstream/python/build/lib.linux-x86_64-cpython-39/', '-DPYTHON_EXECUTABLE=/root/miniconda3/envs/py39/bin/python3.9', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_VERBOSE_MAKEFILE=ON', '-DEXAMPLE_VERSION_INFO=0.0.1', '-GNinja']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rtmp-streaming
  Running setup.py clean for rtmp-streaming
Failed to build rtmp-streaming
ERROR: Could not build wheels for rtmp-streaming, which is required to install pyproject.toml-based projects
```

我是python 3.9，CUDA 11.8，torch 2.1.1+cu118

**Comment by DestoryVIP** [comment]
你好，我也没安装成功，但是这一步我解决了，你直接去克隆pybind11项目然后编译即可，但是后面还有一些列的错误未解决

**Comment by lipku** [comment]
在项目目录下执行 git submodule update --init

**Comment by piwawa** [comment]
谢谢两位的回答，折腾一下午弄好了，步骤是：

1. 手动克隆pybind11
2. 安装ffmpeg
3. 编译 python_rtmpstream

我就是这样安装成功的，不过他那个[直播数字人](https://github.com/lipku/metahuman-stream)部署完没有用，只能无限循环obama摇头晃脑的视频，输入文本不会生成对应的口唇动作。

**Comment by lipku** [comment]
修改echo.html中websocket和视频播放地址，将serverip替换成实际服务器ip.
https://zhuanlan.zhihu.com/p/675131165
