### ISSUE TITLE
执行pip install .报错Could not build wheels for rtmp_streaming，环境mac m3,ffmpeg 6.1.1，py3.10.14

### ISSUE THREAD

**Issue by xy0214** [lipku/python_rtmpstream#31]
执行pip install .也报了ERROR: Could not build wheels for rtmp_streaming, which is required to install pyproject.toml-based projects这个错误
### 环境
- mac m3
- ffmpeg 6.1.1
- py3.10.14
- cmake version 3.29.5

```
pip list
Package    Version
---------- -------
pip        24.0
setuptools 70.0.0
wheel      0.43.0
```

```
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: rtmp_streaming
  Building wheel for rtmp_streaming (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [186 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Building with cfg =  Release
      -- The C compiler identification is AppleClang 15.0.0.15000309
      -- The CXX compiler identification is AppleClang 15.0.0.15000309
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- pybind11 v2.12.0 dev1
      -- Found Python: /opt/anaconda3/envs/python_rtmpstream/bin/python3.10 (found suitable version "3.10.14", minimum required is "3.6") found components: Interpreter Development.Module Development.Embed
      -- Performing Test HAS_FLTO_THIN
      -- Performing Test HAS_FLTO_THIN - Failed
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Configuring done (0.7s)
      -- Generating done (0.0s)
      CMake Warning:
        Manually-specified variables were not used by the project:

          EXAMPLE_VERSION_INFO


      -- Build files have been written to: /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/build/temp.macosx-11.0-arm64-cpython-310
      Change Dir: '/Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/build/temp.macosx-11.0-arm64-cpython-310'

      Run Build Command(s): /opt/homebrew/Cellar/cmake/3.29.5/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile
      /opt/homebrew/Cellar/cmake/3.29.5/bin/cmake -S/Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python -B/Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/build/temp.macosx-11.0-arm64-cpython-310 --check-build-system CMakeFiles/Makefile.cmake 0
      /opt/homebrew/Cellar/cmake/3.29.5/bin/cmake -E cmake_progress_start /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/build/temp.macosx-11.0-arm64-cpython-310/CMakeFiles /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/build/temp.macosx-11.0-arm64-cpython-310//CMakeFiles/progress.marks
      /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/Makefile2 all
      /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/rtmp_streaming.dir/build.make CMakeFiles/rtmp_streaming.dir/depend
      cd /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/build/temp.macosx-11.0-arm64-cpython-310 && /opt/homebrew/Cellar/cmake/3.29.5/bin/cmake -E cmake_depends "Unix Makefiles" /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/build/temp.macosx-11.0-arm64-cpython-310 /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/build/temp.macosx-11.0-arm64-cpython-310 /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/build/temp.macosx-11.0-arm64-cpython-310/CMakeFiles/rtmp_streaming.dir/DependInfo.cmake "--color="
      /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/rtmp_streaming.dir/build.make CMakeFiles/rtmp_streaming.dir/build
      [ 33%] Building CXX object CMakeFiles/rtmp_streaming.dir/rtmp_streaming.cpp.o
      /Library/Developer/CommandLineTools/usr/bin/c++ -Drtmp_streaming_EXPORTS -I/Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/../streamer -I/opt/anaconda3/envs/python_rtmpstream/include -isystem /opt/anaconda3/envs/python_rtmpstream/include/python3.10 -isystem /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/pybind11/include -O3 -DNDEBUG -O3 -std=c++14 -Wall -std=gnu++14 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -fPIC -fvisibility=hidden -flto -MD -MT CMakeFiles/rtmp_streaming.dir/rtmp_streaming.cpp.o -MF CMakeFiles/rtmp_streaming.dir/rtmp_streaming.cpp.o.d -o CMakeFiles/rtmp_streaming.dir/rtmp_streaming.cpp.o -c /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/rtmp_streaming.cpp
      In file included from /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/rtmp_streaming.cpp:12:
      /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/../streamer/streamer.hpp:132:16: warning: 'channel_layout' is deprecated [-Wdeprecated-declarations]
              frame->channel_layout = channel_layout;
                     ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavutil/frame.h:574:5: note: 'channel_layout' has been explicitly marked deprecated here
          attribute_deprecated
          ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
      #    define attribute_deprecated __attribute__((deprecated))
                                                      ^
      1 warning generated.
      [ 66%] Building CXX object CMakeFiles/rtmp_streaming.dir/Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp.o
      /Library/Developer/CommandLineTools/usr/bin/c++ -Drtmp_streaming_EXPORTS -I/Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/../streamer -I/opt/anaconda3/envs/python_rtmpstream/include -isystem /opt/anaconda3/envs/python_rtmpstream/include/python3.10 -isystem /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/pybind11/include -O3 -DNDEBUG -O3 -std=c++14 -Wall -std=gnu++14 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -fPIC -fvisibility=hidden -flto -MD -MT CMakeFiles/rtmp_streaming.dir/Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp.o -MF CMakeFiles/rtmp_streaming.dir/Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp.o.d -o CMakeFiles/rtmp_streaming.dir/Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp.o -c /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp
      In file included from /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp:1:
      /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/../streamer/streamer.hpp:132:16: warning: 'channel_layout' is deprecated [-Wdeprecated-declarations]
              frame->channel_layout = channel_layout;
                     ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavutil/frame.h:574:5: note: 'channel_layout' has been explicitly marked deprecated here
          attribute_deprecated
          ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
      #    define attribute_deprecated __attribute__((deprecated))
                                                      ^
      /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp:28:19: error: use of undeclared identifier 'CLOCK_BOOTTIME'; did you mean '_CLOCK_REALTIME'?
          clock_gettime(CLOCK_BOOTTIME,&now);
                        ^~~~~~~~~~~~~~
                        _CLOCK_REALTIME
      /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include/time.h:154:1: note: '_CLOCK_REALTIME' declared here
      _CLOCK_REALTIME __CLOCK_AVAILABILITY = 0,
      ^
      /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp:39:12: warning: format specifies type 'int' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                 pkt->pts,
                 ^~~~~~~~
      /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp:40:12: warning: format specifies type 'int' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                 pkt->dts,
                 ^~~~~~~~
      /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp:41:12: warning: format specifies type 'int' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                 pkt->duration,
                 ^~~~~~~~~~~~~
      /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp:48:5: warning: 'av_init_packet' is deprecated [-Wdeprecated-declarations]
          av_init_packet(&pkt);
          ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavcodec/packet.h:628:1: note: 'av_init_packet' has been explicitly marked deprecated here
      attribute_deprecated
      ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
      #    define attribute_deprecated __attribute__((deprecated))
                                                      ^
      /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp:138:16: warning: 'channels' is deprecated [-Wdeprecated-declarations]
          codec_ctx->channels = channel;
                     ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavcodec/avcodec.h:1071:5: note: 'channels' has been explicitly marked deprecated here
          attribute_deprecated
          ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
      #    define attribute_deprecated __attribute__((deprecated))
                                                      ^
      /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp:139:16: warning: 'channel_layout' is deprecated [-Wdeprecated-declarations]
          codec_ctx->channel_layout = av_get_default_channel_layout(channel);
                     ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavcodec/avcodec.h:1129:5: note: 'channel_layout' has been explicitly marked deprecated here
          attribute_deprecated
          ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
      #    define attribute_deprecated __attribute__((deprecated))
                                                      ^
      /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp:139:33: warning: 'av_get_default_channel_layout' is deprecated [-Wdeprecated-declarations]
          codec_ctx->channel_layout = av_get_default_channel_layout(channel);
                                      ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavutil/channel_layout.h:505:1: note: 'av_get_default_channel_layout' has been explicitly marked deprecated here
      attribute_deprecated
      ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
      #    define attribute_deprecated __attribute__((deprecated))
                                                      ^
      /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp:379:108: warning: 'channel_layout' is deprecated [-Wdeprecated-declarations]
          audioframe.init(out_codec_audio_ctx->sample_fmt, out_codec_audio_ctx->frame_size, out_codec_audio_ctx->channel_layout);
                                                                                                                 ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavcodec/avcodec.h:1129:5: note: 'channel_layout' has been explicitly marked deprecated here
          attribute_deprecated
          ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
      #    define attribute_deprecated __attribute__((deprecated))
                                                      ^
      /Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp:381:60: warning: 'channels' is deprecated [-Wdeprecated-declarations]
                                            out_codec_audio_ctx->channels, 1))) {
                                                                 ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavcodec/avcodec.h:1071:5: note: 'channels' has been explicitly marked deprecated here
          attribute_deprecated
          ^
      /opt/anaconda3/envs/python_rtmpstream/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
      #    define attribute_deprecated __attribute__((deprecated))
                                                      ^
      10 warnings and 1 error generated.
      make[2]: *** [CMakeFiles/rtmp_streaming.dir/Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp.o] Error 1
      make[1]: *** [CMakeFiles/rtmp_streaming.dir/all] Error 2
      make: *** [all] Error 2

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/setup.py", line 125, in <module>
          setup(
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/python/setup.py", line 116, in build_extension
          subprocess.check_call(
        File "/opt/anaconda3/envs/python_rtmpstream/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rtmp_streaming
  Running setup.py clean for rtmp_streaming
Failed to build rtmp_streaming
ERROR: Could not build wheels for rtmp_streaming, which is required to install pyproject.toml-based projects

```

**Comment by Tanthen** [comment]
/Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp:28:19: error: use of undeclared identifier 'CLOCK_BOOTTIME'; did you mean '_CLOCK_REALTIME'?
          clock_gettime(CLOCK_BOOTTIME,&now);
                        ^~~~~~~~~~~~~~
                        _CLOCK_REALTIME
尝试按照它给出的方案进行修改，将/Users/xiongying/kyl_space/rtmp_test/python_rtmpstream/streamer/streamer.cpp的第28行的clock_gettime(CLOCK_BOOTTIME,&now);中的CLOCK_BOOTTIME修改为_CLOCK_REALTIME，这个问题的产生可能源自于你系统库中提供的全局命名(/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include/time.h)与该项目中所用到的命名不同：
