### ISSUE TITLE
请教一下，编译报错

### ISSUE THREAD

**Issue by westernbuptboy** [lipku/python_rtmpstream#4]
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing /data/code/metahuman-stream/python_rtmpstream/python
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: rtmp-streaming
  Building wheel for rtmp-streaming (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [87 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Building with cfg =  Release
      -- The C compiler identification is GNU 9.4.0
      -- The CXX compiler identification is GNU 9.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- pybind11 v2.12.0 dev1
      -- Found PythonInterp: /home/student1/anaconda3/envs/ernerf/bin/python3.10 (found suitable version "3.10.12", minimum required is "3.6")
      -- Found PythonLibs: /home/student1/anaconda3/envs/ernerf/lib/libpython3.10.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Configuring done
      CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
      Please set them or make sure they are set and tested correctly in the CMake files:
      AVCODEC_LIBRARY
          linked by target "rtmp_streaming" in directory /data/code/metahuman-stream/python_rtmpstream/python
      AVFORMAT_LIBRARY
          linked by target "rtmp_streaming" in directory /data/code/metahuman-stream/python_rtmpstream/python
      AVUTIL_LIBRARY
          linked by target "rtmp_streaming" in directory /data/code/metahuman-stream/python_rtmpstream/python
      SWSCALE_LIBRARY
          linked by target "rtmp_streaming" in directory /data/code/metahuman-stream/python_rtmpstream/python

      -- Generating done
      CMake Warning:
        Manually-specified variables were not used by the project:

          EXAMPLE_VERSION_INFO

      CMake Generate step failed.  Build files cannot be regenerated correctly.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/code/metahuman-stream/python_rtmpstream/python/setup.py", line 125, in <module>
          setup(
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/data/code/metahuman-stream/python_rtmpstream/python/setup.py", line 113, in build_extension
          subprocess.check_call(
        File "/home/user/.conda/envs/ernerf/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/data/code/metahuman-stream/python_rtmpstream/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/code/metahuman-stream/python_rtmpstream/python/build/lib.linux-x86_64-cpython-310/', '-DPYTHON_EXECUTABLE=/home/user/.conda/envs/ernerf/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_VERBOSE_MAKEFILE=ON', '-DEXAMPLE_VERSION_INFO=0.0.1', '-GNinja']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rtmp-streaming
  Running setup.py clean for rtmp-streaming

**Comment by Tiandishihua** [comment]
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple Processing /data/code/metahuman-stream/python_rtmpstream/python Preparing metadata (setup.py) ... done Building wheels for collected packages: rtmp-streaming Building wheel for rtmp-streaming (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [87 lines of output] running bdist_wheel running build running build_ext Building with cfg = Release -- The C compiler identification is GNU 9.4.0 -- The CXX compiler identification is GNU 9.4.0 -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Check for working C compiler: /usr/bin/cc - skipped -- Detecting C compile features -- Detecting C compile features - done -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Check for working CXX compiler: /usr/bin/c++ - skipped -- Detecting CXX compile features -- Detecting CXX compile features - done -- pybind11 v2.12.0 dev1 -- Found PythonInterp: /home/student1/anaconda3/envs/ernerf/bin/python3.10 (found suitable version "3.10.12", minimum required is "3.6") -- Found PythonLibs: /home/student1/anaconda3/envs/ernerf/lib/libpython3.10.so -- Performing Test HAS_FLTO -- Performing Test HAS_FLTO - Success -- Configuring done CMake Error: The following variables are used in this project, but they are set to NOTFOUND. Please set them or make sure they are set and tested correctly in the CMake files: AVCODEC_LIBRARY linked by target "rtmp_streaming" in directory /data/code/metahuman-stream/python_rtmpstream/python AVFORMAT_LIBRARY linked by target "rtmp_streaming" in directory /data/code/metahuman-stream/python_rtmpstream/python AVUTIL_LIBRARY linked by target "rtmp_streaming" in directory /data/code/metahuman-stream/python_rtmpstream/python SWSCALE_LIBRARY linked by target "rtmp_streaming" in directory /data/code/metahuman-stream/python_rtmpstream/python
> 
> ```
>   -- Generating done
>   CMake Warning:
>     Manually-specified variables were not used by the project:
> 
>       EXAMPLE_VERSION_INFO
> 
> 
>   CMake Generate step failed.  Build files cannot be regenerated correctly.
>   Traceback (most recent call last):
>     File "<string>", line 2, in <module>
>     File "<pip-setuptools-caller>", line 34, in <module>
>     File "/data/code/metahuman-stream/python_rtmpstream/python/setup.py", line 125, in <module>
>       setup(
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
>       return distutils.core.setup(**attrs)
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
>       return run_commands(dist)
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
>       dist.run_commands()
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
>       self.run_command(cmd)
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
>       super().run_command(command)
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>       cmd_obj.run()
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run
>       self.run_command("build")
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
>       self.distribution.run_command(command)
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
>       super().run_command(command)
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>       cmd_obj.run()
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
>       self.run_command(cmd_name)
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
>       self.distribution.run_command(command)
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
>       super().run_command(command)
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>       cmd_obj.run()
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
>       _build_ext.run(self)
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
>       self.build_extensions()
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
>       self._build_extensions_serial()
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
>       self.build_extension(ext)
>     File "/data/code/metahuman-stream/python_rtmpstream/python/setup.py", line 113, in build_extension
>       subprocess.check_call(
>     File "/home/user/.conda/envs/ernerf/lib/python3.10/subprocess.py", line 369, in check_call
>       raise CalledProcessError(retcode, cmd)
>   subprocess.CalledProcessError: Command '['cmake', '/data/code/metahuman-stream/python_rtmpstream/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/code/metahuman-stream/python_rtmpstream/python/build/lib.linux-x86_64-cpython-310/', '-DPYTHON_EXECUTABLE=/home/user/.conda/envs/ernerf/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_VERBOSE_MAKEFILE=ON', '-DEXAMPLE_VERSION_INFO=0.0.1', '-GNinja']' returned non-zero exit status 1.
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for rtmp-streaming Running setup.py clean for rtmp-streaming

请问您解决了吗

**Comment by SSSh1wein4n** [comment]
检查一下CMakeLists.txt文件里find_library()里配置的几个地址。
