### ISSUE TITLE
pip install . 编译问题

### ISSUE THREAD

**Issue by aoyang-hd** [lipku/python_rtmpstream#6]
我是先安装了https://github.com/lipku/metahuman-stream?tab=readme-ov-file
Install dependency
conda create -n nerfstream python=3.10
conda install pytorch==1.12.1 torchvision==0.13.1 cudatoolkit=11.3 -c pytorch
conda activate nerfstream
pip install -r requirements.txt
pip install "git+https://github.com/facebookresearch/pytorch3d.git"
pip install tensorflow-gpu==2.8.0

然后参考了这个问题 https://github.com/lipku/python_rtmpstream/issues/3
安装了
手动克隆pybind11
安装ffmpeg

还是有问题
Looking in indexes: https://mirrors.aliyun.com/pypi/simple, https://pypi.ngc.nvidia.com
Processing /data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: rtmp-streaming
  Building wheel for rtmp-streaming (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Building with cfg =  Release
      -- The C compiler identification is GNU 9.3.0
      -- The CXX compiler identification is GNU 9.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at CMakeLists.txt:57 (add_subdirectory):
        add_subdirectory given source "pybind11" which is not an existing
        directory.
      
      
      CMake Error at CMakeLists.txt:58 (pybind11_add_module):
        Unknown CMake command "pybind11_add_module".
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python/setup.py", line 125, in <module>
          setup(
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python/setup.py", line 113, in build_extension
          subprocess.check_call(
        File "/home/cv/.conda/envs/nerfstream/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python/build/lib.linux-x86_64-cpython-310/', '-DPYTHON_EXECUTABLE=/home/cv/.conda/envs/nerfstream/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_VERBOSE_MAKEFILE=ON', '-DEXAMPLE_VERSION_INFO=0.0.1', '-GNinja']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rtmp-streaming
  Running setup.py clean for rtmp-streaming
Failed to build rtmp-streaming

**Comment by lipku** [comment]
$ cd python_rtmpstream
$ git submodule update --init

**Comment by aoyang-hd** [comment]
还是不行，错误一样

**Comment by aoyang-hd** [comment]
您好我在服务器上通过
docker run --rm -it -p 1935:1935 -p 1985:1985 -p 8080:8080 registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5
docker run --gpus all -it --network=host --rm  registry.cn-hangzhou.aliyuncs.com/lipku/nerfstream:v1.2
启动起来了docker 然后我该怎么访问服务器上的地址  我的服务器地址是10.6.16.95

**Comment by lipku** [comment]
用vlc访问或者用浏览器访问nginx地址，readme里有

**Comment by aoyang-hd** [comment]
> 用vlc访问或者用浏览器访问nginx地址，readme里有

![image](https://github.com/lipku/python_rtmpstream/assets/83214696/b1c6f5ab-6906-40f0-810c-e224fcc21204)
我启动的docker里面 没有echo.html和mpegts-1.7.3.min.js 文件 只有test.html 是否是修改test.html中的ip地址

test.html 和你项目的echo.html也不一样

**Comment by Kedreamix** [comment]
@aoyang-hd 你好，你之前的问题是怎么解决呢，好像issue没有说你是最后怎么解决的？

**Comment by Tiandishihua** [comment]
> 我是先安装了https://github.com/lipku/metahuman-stream?tab=readme-ov-file Install dependency conda create -n nerfstream python=3.10 conda install pytorch==1.12.1 torchvision==0.13.1 cudatoolkit=11.3 -c pytorch conda activate nerfstream pip install -r requirements.txt pip install "git+https://github.com/facebookresearch/pytorch3d.git" pip install tensorflow-gpu==2.8.0
> 
> 然后参考了这个问题 #3 安装了 手动克隆pybind11 安装ffmpeg
> 
> 还是有问题 Looking in indexes: https://mirrors.aliyun.com/pypi/simple, https://pypi.ngc.nvidia.com Processing /data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python Preparing metadata (setup.py) ... done Building wheels for collected packages: rtmp-streaming Building wheel for rtmp-streaming (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [72 lines of output] running bdist_wheel running build running build_ext Building with cfg = Release -- The C compiler identification is GNU 9.3.0 -- The CXX compiler identification is GNU 9.3.0 -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Check for working C compiler: /usr/bin/cc - skipped -- Detecting C compile features -- Detecting C compile features - done -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Check for working CXX compiler: /usr/bin/c++ - skipped -- Detecting CXX compile features -- Detecting CXX compile features - done CMake Error at CMakeLists.txt:57 (add_subdirectory): add_subdirectory given source "pybind11" which is not an existing directory.
> 
> ```
>   CMake Error at CMakeLists.txt:58 (pybind11_add_module):
>     Unknown CMake command "pybind11_add_module".
>   
>   
>   -- Configuring incomplete, errors occurred!
>   Traceback (most recent call last):
>     File "<string>", line 2, in <module>
>     File "<pip-setuptools-caller>", line 34, in <module>
>     File "/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python/setup.py", line 125, in <module>
>       setup(
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
>       return distutils.core.setup(**attrs)
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
>       return run_commands(dist)
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
>       dist.run_commands()
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
>       self.run_command(cmd)
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
>       super().run_command(command)
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>       cmd_obj.run()
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run
>       self.run_command("build")
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
>       self.distribution.run_command(command)
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
>       super().run_command(command)
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>       cmd_obj.run()
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
>       self.run_command(cmd_name)
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
>       self.distribution.run_command(command)
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
>       super().run_command(command)
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>       cmd_obj.run()
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
>       _build_ext.run(self)
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
>       self.build_extensions()
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
>       self._build_extensions_serial()
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
>       self.build_extension(ext)
>     File "/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python/setup.py", line 113, in build_extension
>       subprocess.check_call(
>     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/subprocess.py", line 369, in check_call
>       raise CalledProcessError(retcode, cmd)
>   subprocess.CalledProcessError: Command '['cmake', '/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python/build/lib.linux-x86_64-cpython-310/', '-DPYTHON_EXECUTABLE=/home/cv/.conda/envs/nerfstream/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_VERBOSE_MAKEFILE=ON', '-DEXAMPLE_VERSION_INFO=0.0.1', '-GNinja']' returned non-zero exit status 1.
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for rtmp-streaming Running setup.py clean for rtmp-streaming Failed to build rtmp-streaming

请问您解决了吗

**Comment by aoyang-hd** [comment]
> > 我是先安装了https://github.com/lipku/metahuman-stream?tab=readme-ov-file Install dependency conda create -n nerfstream python=3.10 conda install pytorch==1.12.1 torchvision==0.13.1 cudatoolkit=11.3 -c pytorch conda activate nerfstream pip install -r requirements.txt pip install "git+https://github.com/facebookresearch/pytorch3d.git" pip install tensorflow-gpu==2.8.0
> > 然后参考了这个问题 #3 安装了 手动克隆pybind11 安装ffmpeg
> > 还是有问题 Looking in indexes: https://mirrors.aliyun.com/pypi/simple, https://pypi.ngc.nvidia.com Processing /data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python Preparing metadata (setup.py) ... done Building wheels for collected packages: rtmp-streaming Building wheel for rtmp-streaming (setup.py) ... error error: subprocess-exited-with-error
> > × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [72 lines of output] running bdist_wheel running build running build_ext Building with cfg = Release -- The C compiler identification is GNU 9.3.0 -- The CXX compiler identification is GNU 9.3.0 -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Check for working C compiler: /usr/bin/cc - skipped -- Detecting C compile features -- Detecting C compile features - done -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Check for working CXX compiler: /usr/bin/c++ - skipped -- Detecting CXX compile features -- Detecting CXX compile features - done CMake Error at CMakeLists.txt:57 (add_subdirectory): add_subdirectory given source "pybind11" which is not an existing directory.
> > ```
> >   CMake Error at CMakeLists.txt:58 (pybind11_add_module):
> >     Unknown CMake command "pybind11_add_module".
> >   
> >   
> >   -- Configuring incomplete, errors occurred!
> >   Traceback (most recent call last):
> >     File "<string>", line 2, in <module>
> >     File "<pip-setuptools-caller>", line 34, in <module>
> >     File "/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python/setup.py", line 125, in <module>
> >       setup(
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
> >       return distutils.core.setup(**attrs)
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
> >       return run_commands(dist)
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
> >       dist.run_commands()
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
> >       self.run_command(cmd)
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
> >       super().run_command(command)
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
> >       cmd_obj.run()
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run
> >       self.run_command("build")
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
> >       self.distribution.run_command(command)
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
> >       super().run_command(command)
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
> >       cmd_obj.run()
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
> >       self.run_command(cmd_name)
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
> >       self.distribution.run_command(command)
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
> >       super().run_command(command)
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
> >       cmd_obj.run()
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
> >       _build_ext.run(self)
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
> >       self.build_extensions()
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
> >       self._build_extensions_serial()
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
> >       self.build_extension(ext)
> >     File "/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python/setup.py", line 113, in build_extension
> >       subprocess.check_call(
> >     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/subprocess.py", line 369, in check_call
> >       raise CalledProcessError(retcode, cmd)
> >   subprocess.CalledProcessError: Command '['cmake', '/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python/build/lib.linux-x86_64-cpython-310/', '-DPYTHON_EXECUTABLE=/home/cv/.conda/envs/nerfstream/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_VERBOSE_MAKEFILE=ON', '-DEXAMPLE_VERSION_INFO=0.0.1', '-GNinja']' returned non-zero exit status 1.
> >   [end of output]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for rtmp-streaming Running setup.py clean for rtmp-streaming Failed to build rtmp-streaming
> 
> 请问您解决了吗

这个项目的问题没解决

我转战其他数字人项目了，有兴趣你可以试试
https://github.com/waityousea/xuniren
这个也有坑，不过我解决了，遇到了你看看Issues 我发里面了

**Comment by aoyang-hd** [comment]
> @aoyang-hd 你好，你之前的问题是怎么解决呢，好像issue没有说你是最后怎么解决的？
这个问题我没解决
我后面直接用docker启动，但是也一直没连上，没成功

**Comment by Tiandishihua** [comment]
好的，非常感谢您的回复和热心帮助。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lipku/python_rtmpstream"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月25日(星期四) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lipku/python_rtmpstream] pip install . 编译问题 (Issue #6)





   
我是先安装了https://github.com/lipku/metahuman-stream?tab=readme-ov-file Install dependency conda create -n nerfstream python=3.10 conda install pytorch==1.12.1 torchvision==0.13.1 cudatoolkit=11.3 -c pytorch conda activate nerfstream pip install -r requirements.txt pip install "git+https://github.com/facebookresearch/pytorch3d.git" pip install tensorflow-gpu==2.8.0
 然后参考了这个问题 #3 安装了 手动克隆pybind11 安装ffmpeg
 还是有问题 Looking in indexes: https://mirrors.aliyun.com/pypi/simple, https://pypi.ngc.nvidia.com Processing /data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python Preparing metadata (setup.py) ... done Building wheels for collected packages: rtmp-streaming Building wheel for rtmp-streaming (setup.py) ... error error: subprocess-exited-with-error
 × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─&gt; [72 lines of output] running bdist_wheel running build running build_ext Building with cfg = Release -- The C compiler identification is GNU 9.3.0 -- The CXX compiler identification is GNU 9.3.0 -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Check for working C compiler: /usr/bin/cc - skipped -- Detecting C compile features -- Detecting C compile features - done -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Check for working CXX compiler: /usr/bin/c++ - skipped -- Detecting CXX compile features -- Detecting CXX compile features - done CMake Error at CMakeLists.txt:57 (add_subdirectory): add_subdirectory given source "pybind11" which is not an existing directory.
   CMake Error at CMakeLists.txt:58 (pybind11_add_module):     Unknown CMake command "pybind11_add_module".         -- Configuring incomplete, errors occurred!   Traceback (most recent call last):     File "<string&gt;", line 2, in <module&gt;     File "<pip-setuptools-caller&gt;", line 34, in <module&gt;     File "/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python/setup.py", line 125, in <module&gt;       setup(     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup       return distutils.core.setup(**attrs)     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup       return run_commands(dist)     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands       dist.run_commands()     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands       self.run_command(cmd)     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command       super().run_command(command)     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command       cmd_obj.run()     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run       self.run_command("build")     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command       self.distribution.run_command(command)     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command       super().run_command(command)     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command       cmd_obj.run()     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run       self.run_command(cmd_name)     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command       self.distribution.run_command(command)     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command       super().run_command(command)     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command       cmd_obj.run()     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run       _build_ext.run(self)     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run       self.build_extensions()     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions       self._build_extensions_serial()     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial       self.build_extension(ext)     File "/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python/setup.py", line 113, in build_extension       subprocess.check_call(     File "/home/cv/.conda/envs/nerfstream/lib/python3.10/subprocess.py", line 369, in check_call       raise CalledProcessError(retcode, cmd)   subprocess.CalledProcessError: Command '['cmake', '/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/cv/aoyang/metahuman-stream-main/python_rtmpstream-main/python/build/lib.linux-x86_64-cpython-310/', '-DPYTHON_EXECUTABLE=/home/cv/.conda/envs/nerfstream/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_VERBOSE_MAKEFILE=ON', '-DEXAMPLE_VERSION_INFO=0.0.1', '-GNinja']' returned non-zero exit status 1.   [end of output]  
note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for rtmp-streaming Running setup.py clean for rtmp-streaming Failed to build rtmp-streaming
  
请问您解决了吗
  
这个项目的问题没解决
 
我转战其他数字人项目了，有兴趣你可以试试
 https://github.com/waityousea/xuniren
 这个也有坑，不过我解决了，遇到了你看看Issues 我发里面了

**Comment by cacard** [comment]
这个应该是 so 没找到，
在 CMakeLists.txt 中：

改成，参考我下面的代码，判定 so 到底有没有找到：

find_library(AVCODEC_LIBRARY libavcodec.so /usr/lib/x86_64-linux-gnu/) #  
if(AVCODEC_LIBRARY)
    message(STATUS "Found AVCODEC_LIBRARY library at ${AVCODEC_LIBRARY} ---------------------------")
else()
    message(WARNING "AVCODEC_LIBRARY library not found -------------------------------")
endif()

find_library(AVFORMAT_LIBRARY libavformat.so /usr/lib/x86_64-linux-gnu/)
if(AVFORMAT_LIBRARY)
    message(STATUS "Found AVFORMAT_LIBRARY library at ${AVFORMAT_LIBRARY} ---------------------------")
else()
    message(WARNING "AVFORMAT_LIBRARY library not found -------------------------------")
endif()


find_library(AVUTIL_LIBRARY libavutil.so /usr/lib/x86_64-linux-gnu/)
if(AVUTIL_LIBRARY)
    message(STATUS "Found AVUTIL_LIBRARY library at ${AVUTIL_LIBRARY} ---------------------------")
else()
    message(WARNING "AVUTIL_LIBRARY library not found -------------------------------")
endif()

find_library(SWSCALE_LIBRARY libswscale.so /usr/lib/x86_64-linux-gnu/)
if(SWSCALE_LIBRARY)
    message(STATUS "Found SWSCALE_LIBRARY library at ${SWSCALE_LIBRARY} ---------------------------")
else()
    message(WARNING "SWSCALE_LIBRARY library not found -------------------------------")
endif()

编译安装时，看LOG看看到底有没有找到so。
另外
find_library(SWSCALE_LIBRARY swscale /usr/lib/x86_64-linux-gnu/)
默认是先找.a
改成：
find_library(SWSCALE_LIBRARY libswscale.so /usr/lib/x86_64-linux-gnu/)
默认是找.so

重要：根据你自己的系统设定合适的/usr/lib/x86_64-linux-gnu/路径，确保下面有对应的 .so
